### ISSUE TITLE
CGI.parse undefined in Ruby 4.0 breaks syntax highlighting (NoMethodError via rouge)

### ISSUE THREAD

**Issue by danielb2** [piotrmurach/tty-markdown#32]
### Describe the problem
On Ruby 4.0, calling `TTY::Markdown.parse` on content containing a fenced code block raises `NoMethodError: undefined method 'parse' for class CGI`. This comes from rouge's `Lexer.lookup_fancy`, which calls `CGI.parse`, via tty-markdown's `SyntaxHighliter.highlight` in `convert_codespan`/`convert_codeblock`. Ruby 4.0 removed the `cgi` standard library (only the smaller `cgi/escape` remains), so `CGI.parse` is no longer available unless something explicitly requires the old `cgi` library.

### Steps to reproduce the problem
````ruby
require "tty-markdown"

markdown = <<~MD
  # Example

  ```ruby
  puts "hello"
  ```
MD

TTY::Markdown.parse(markdown)
````

### Actual behaviour
```
/path/to/gems/rouge-3.28.0/lib/rouge/lexer.rb:55:in 'Rouge::Lexer.lookup_fancy': undefined method 'parse' for class CGI (NoMethodError)
        opts = CGI.parse(opts || '').map do |k, vals|
                  ^^^^^^
	from rouge-3.28.0/lib/rouge/lexer.rb:95:in 'Rouge::Lexer.find_fancy'
	from tty-markdown-0.7.2/lib/tty/markdown/syntax_highlighter.rb:57:in 'TTY::Markdown::SyntaxHighliter.highlight'
	from tty-markdown-0.7.2/lib/tty/markdown/converter.rb:236:in 'TTY::Markdown::Converter#convert_codespan'
	from tty-markdown-0.7.2/lib/tty/markdown/converter.rb:253:in 'TTY::Markdown::Converter#convert_codeblock'
	...
	from tty-markdown-0.7.2/lib/tty/markdown.rb:144:in 'TTY::Markdown.parse'
```

### Expected behaviour
`TTY::Markdown.parse` should render fenced code blocks with syntax highlighting without raising, the same as on Ruby 3.x. Either tty-markdown (or one of its dependencies, rouge) needs to `require "cgi"` explicitly, or tty-markdown should avoid depending on code paths that rely on the now-removed `cgi` stdlib (e.g. by bumping the `rouge` dependency to a version that doesn't use `CGI.parse`, or requiring `cgi` itself as a workaround).

### Describe your environment
* OS version:
* Ruby version: 4.0.4
* TTY::Markdown version: 0.7.2 (rouge 3.28.0, kramdown 2.5.2)

**Comment by piotrmurach** [comment]
Hi Daniel, 👋 

Thank you for using the `tty-markdown` gem. 🙏 

The `tty-markdown` works on Ruby `4.0` as evidenced by the [CI run](https://github.com/piotrmurach/tty-markdown/actions/runs/22975123440). The issue described has been resolved in the `rouge` gem version `4.6.1` [last year](https://github.com/rouge-ruby/rouge/pull/2131). As an aside, I encountered this issue on Ruby `3.5.0` preview builds.

Now, the reported issue is that the `rouge` version `3.28.0` language detection doesn't work on Ruby `4.0`. It's important to note here that this version is relatively old and about 20 versions behind the latest release.

To use such an old release of the `rouge` gem on the latest Ruby, there are two options. Option one is to add the `cgi` dependency to the `Gemfile` or `gemspec` file. Alternatively, submit an issue to the `rouge` project to backport the fix to the `3.x` series. I would suggest upgrading the `rouge` gem itself if possible.

In either case, it's not on `tty-markdown` to facilitate outdated dependencies that may cause issues on the latest Ruby releases. The issue isn't affecting more recent releases of the `rouge` gem, which is most important. This gem allows installation of older versions of the `rouge` gem to support older Ruby releases. But the responsibility falls on the developer to upgrade their dependencies to the latest. Therefore, this is not a bug in `tty-markdown`, and nothing needs to change.

**Comment by danielb2** [comment]
Hi, thanks for the detailed response! 👋

I understand the root cause is in `rouge` 3.x and that `rouge` 4.6.1 fixed it. However, the core issue remains: running `gem install tty-markdown` on Ruby `4.0` silently produces a broken installation. I didn't pin `rouge` to `3.28.0` myself, that's what RubyGems resolved when installing `tty-markdown`.

The argument that older `rouge` versions exist to support older Ruby releases doesn't quite hold up here, because those older versions are broken on Ruby `4.0`. A developer on Ruby `4.0` doing a fresh install gets a setup that doesn't work, with no warning.

Setting a minimum `rouge` version that excludes broken versions on Ruby `4.0` would solve this. Alternatively, even a note in the README would help. As it stands, `tty-markdown` advertises Ruby `4.0` support via CI, but a clean `gem install` on Ruby `4.0` is broken out of the box.

**Comment by piotrmurach** [comment]
> I understand the root cause is in rouge 3.x and that rouge 4.6.1 fixed it.

Given the recommendation:

> (or one of its dependencies, rouge) needs to require "cgi" explicitly

I assumed a lack of awareness about the `rouge` gem being fixed.

> However, the core issue remains: running gem install tty-markdown on Ruby 4.0 silently produces a broken installation.

No, it does not.

Let's run the provided code snippet as `hello.rb` in a container to disprove this.

Here's a minimal Dockerfile based on the official Ruby `4.0.5` image that installs only the `tty-markdown`:

```Dockerfile
FROM ruby:4.0.5

COPY hello.rb .

CMD sh -c "gem install tty-markdown && ruby hello.rb"
```

And that's the output I get:

```
Successfully installed tty-screen-0.8.2
Successfully installed tty-color-0.6.0
Successfully installed unicode_utils-1.4.0
Successfully installed unicode-display_width-2.6.0
Successfully installed strings-ansi-0.2.0
Successfully installed strings-0.2.1
Successfully installed rouge-4.7.0
Successfully installed pastel-0.8.0
Successfully installed kramdown-2.5.2
Successfully installed tty-markdown-0.7.2
10 gems installed
Example

puts "hello"
```

The container installs the `rouge` version `4.7.0`, and the code snippet runs fine. Note that it installs the latest version of every gem.

>  I didn't pin rouge to 3.28.0 myself, that's what RubyGems resolved when installing tty-markdown.

The `rouge` version `3.28.0` most likely wasn't downloaded with the `tty-markdown` installation. The `rubygems` resolved to this locally preinstalled version as it met the `rouge` gem installation constraint specified by the `tty-markdown`. How did this version get there? Given myriad ways to manage Ruby and gems, this is a rabbit hole I have no intention of going down.

 > The argument that older rouge versions exist to support older Ruby releases doesn't quite hold up here, because those older versions are broken on Ruby 4.0. 

The `rouge` gem constraint in `tty-markdown` exists the way it does as mentioned here:

> This gem allows installation of older versions of the rouge gem to support older Ruby releases.

The `tty-markdown` gem can be installed on Ruby `2.0` through `4.0`. What `rouge` version is installed depends on the Ruby version. For example, on Ruby `2.5`, the `rouge` gem version `3.30.0` is installed as permitted by the `tty-markdown` constraints. This flexibility means that it's possible to mix a very old `rouge` gem version with the newest Ruby release. That's a gemspec limitation.

> Setting a minimum rouge version that excludes broken versions on Ruby 4.0 would solve this.

That would solve it for Ruby `4.0`, but not for other versions, such as the previously mentioned Ruby `2.5`. I do not plan to limit supported Ruby versions.

> As it stands, tty-markdown advertises Ruby 4.0 support via CI, but a clean gem install on Ruby 4.0 is broken out of the box.

The GitHub CI is not here for advertisement. It runs tests in an isolated environment, assuring that the gem works on various pristine Ruby installations. Consequently, it disproves problems like these, which are affected by local configuration and installation.
